#! /bin/sh

# Autostart applications
pgrep -x sxhkd > /dev/null || sxhkd & #launches sxhkd
picom & #launches compositor
nitrogen --restore & #sets wallpaper
emacs --daemon & #launches emacs daemon
dunst & #launches notification daemon

# Monitor setup
~/.config/bspwm/scripts/monitors.sh &
~/.config/polybar/launch.sh & #launches polybar

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 0

# Window configuration
bspc config border_width         3
bspc config window_gap           5
bspc config remove_disabled_monitors true #should remove disabled monitors
bspc config remove_unplugged_monitors true #should remove unplugged monitors

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# BSPWM Colours
bspc config normal_border_color    "#282828"
bspc config active_border_color    "#689D6A"
bspc config focused_border_color   "#458588"
bspc config presel_feedback_color  "#458588"
bspc config urgent_border_color    "#CC241D"

# Window and workspace rules
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a zoom state=floating
